### ISSUE TITLE
Tinynumpy not available on PyPI

### ISSUE THREAD

**Issue by eayoungs** [wadetb/tinynumpy#17]
Wade,
    I'd like to use tinynumpy in another project, [eppy](https://github.com/santoshphilip/eppy). It would be nice to be able to import it rather than including the files in our project so that we can keep everything up to date with the least effort.
    Let me know if anyone is planning on doing this already, or would be willing to take it up. Otherwise I could take a stab at it, if you're OK with that.

Cheers

Eric

**Comment by wadetb** [comment]
Apologies for taking so long to reply (and to integrate your math changes).  I've never added a package to PyPI before; if you'd like to tackle it that would be wonderful.

I've given you commit access based on the quality of your other changes; feel free to add any manifest files or whatever is required by PyPI.

**Comment by eayoungs** [comment]
No worries, Wade. Thanks for your vote of confidence. I would be glad to take on adding tinynumpy to PyPI

Cheers

Eric

**Comment by eayoungs** [comment]
Wade,
    The project is now available on PyPI @ [https://pypi.python.org/pypi/tinynumpy/1.2.0.dev1](https://pypi.python.org/pypi/tinynumpy/1.2.0.dev1).

**Comment by wadetb** [comment]
Looks great, thanks for taking care of it!  If the format allows multiple authors, please add Almar Klein as well.

**Comment by eayoungs** [comment]
Done!--finally. ;-)

**Comment by eayoungs** [comment]
A

**Comment by eayoungs** [comment]
If anyone was having trouble installing from pip, try it again. I've made some changes and it should work now. Let me know if it doesn't.

**Comment by eayoungs** [comment]
Although the package was uploaded, it was not available to other projects on import. I'll have to give this one another try. If anyone has experience with this, help would be greatly appreciated at this point.

Cheers

Eric

**Comment by eayoungs** [comment]
I've successfully re-uploaded to PyPI, but I'm unable to get pip install to work. Can someone else give it a try, and let me know what happens?

Thanks

Eric
